# Generated by Django 3.2 on 2022-12-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='inn',
            field=models.CharField(default='', max_length=255),
        ),
    ]
