# Generated by Django 3.2 on 2022-12-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221222_0043'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Msg',
            new_name='EmailEntry',
        ),
    ]
